"use client";
import React from "react";
import Navbar from "./Navbar";

const PrivacyPolicy = () => {
  return (
    <div id="privacy" className="bg-[#12171B] text-white">
      <div className="mycontainer py-16">
        {/*  Header */}
        <div className=" mb-12">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">
            Privacy Policy
          </h1>

          <p className="text-zinc-400 mb-6">Last updated: September 14, 2025</p>

          <p className="text-white text-base md:text-lg leading-relaxed">
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
            <br />
            <br />
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy. This Privacy
            Policy has been created with the help of the Privacy Policy
            Generator.
          </p>
        </div>

        {/* Content */}
        <div className=" space-y-12 text-base md:text-lg leading-relaxed text-white">
          {/* Interpretation */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              Interpretation and Definitions
            </h2>

            <h3 className="text-xl font-medium text-white mb-2">
              Interpretation
            </h3>

            <p>
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>
          </section>

          {/* Definitions */}
          <section>
            <h3 className="text-xl font-medium text-white mb-3">Definitions</h3>

            <p className="mb-4">For the purposes of this Privacy Policy:</p>

            <ul className="list-disc list-inside space-y-3">
              <li>
                <strong>Account</strong> means a unique account created for You
                to access our Service or parts of our Service.
              </li>
              <li>
                <strong>Affiliate</strong> means an entity that controls, is
                controlled by or is under common control with a party.
              </li>
              <li>
                <strong>Application</strong> refers to Pixelift, the software
                program provided by the Company.
              </li>
              <li>
                <strong>Company</strong> (referred to as "We", "Us" or "Our")
                refers to Pixelift.
              </li>
              <li>
                <strong>Country</strong> refers to: Pakistan.
              </li>
              <li>
                <strong>Device</strong> means any device that can access the
                Service such as a computer, a cellphone or a digital tablet.
              </li>
              <li>
                <strong>Personal Data</strong> is any information that relates
                to an identified or identifiable individual.
              </li>
              <li>
                <strong>Service</strong> refers to the Application.
              </li>
              <li>
                <strong>Service Provider</strong> means any natural or legal
                person who processes the data on behalf of the Company.
              </li>
              <li>
                <strong>Usage Data</strong> refers to data collected
                automatically, either generated by the use of the Service or
                from the Service infrastructure itself.
              </li>
              <li>
                <strong>You</strong> means the individual accessing or using the
                Service.
              </li>
            </ul>
          </section>

          {/* Collecting Data */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              Collecting and Using Your Personal Data
            </h2>

            <h3 className="text-xl font-medium text-white mb-2">
              Types of Data Collected
            </h3>

            <h4 className="font-semibold text-white mt-4 mb-2">
              Personal Data
            </h4>

            <p>
              While using Our Service, We may ask You to provide Us with certain
              personally identifiable information that can be used to contact or
              identify You. Personally identifiable information may include, but
              is not limited to:
            </p>

            <h4 className="font-semibold text-white mt-6 mb-2">Usage Data</h4>

            <p>
              Usage Data may include information such as Your Device's Internet
              Protocol address (e.g. IP address), browser type, browser version,
              the pages of our Service that You visit, the time and date of Your
              visit, the time spent on those pages, unique device identifiers
              and other diagnostic data.
            </p>
          </section>

          {/* App Usage */}
          <section>
            <h3 className="text-xl font-medium text-white mb-3">
              Information Collected while Using the Application
            </h3>

            <p>
              While using Our Application, in order to provide features of Our
              Application, We may collect, with Your prior permission, pictures
              and other information from your Device's camera and photo library.
              You can enable or disable access to this information at any time
              through Your Device settings.
            </p>
          </section>

          {/* Retention */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              Retention of Your Personal Data
            </h2>

            <p>
              The Company will retain Your Personal Data only for as long as is
              necessary for the purposes set out in this Privacy Policy and to
              comply with legal obligations.<br></br>
              The Company will also retain Usage Data for internal analysis
              purposes. Usage Data is generally retained for a shorter period of
              time, except when this data is used to strengthen the security or
              to improve the functionality of Our Service, or We are legally
              obligated to retain this data for longer time periods.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              Transfer of Your Personal Data
            </h2>

            <p>
              Your information, including Personal Data, is processed at the
              Company's operating offices and in any other places where the
              parties involved in the processing are located. It means that this
              information may be transferred to — and maintained on — computers
              located outside of Your state, province, country or other
              governmental jurisdiction where the data protection laws may
              differ than those from Your jurisdiction.<br></br>
              Your consent to this Privacy Policy followed by Your submission of
              such information represents Your agreement to that transfer.
            </p>
          </section>

          {/* Contact Us */}
          <section className="border-t border-[#2D3845] pt-10 mt-14">
            <h2 className="text-3xl font-bold text-white mb-6">Contact Us</h2>

            <p className="text-white mb-6">
              If you have any questions about this Privacy Policy, You can
              contact us:
            </p>

            <ul className="list-disc list-inside space-y-4 text-white">
              <li>
                By email:{" "}
                <a
                  href="mailto:hello@devsrank.com"
                  className="text-[#AABFFF] underline"
                >
                  Hello@devsrank.com
                </a>
              </li>

              <li>
                By visiting this page on our website:{" "}
                <a
                  href="https://devsrank.com/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[#AABFFF] underline"
                >
                  https://devsrank.com/
                </a>
              </li>

              <li>
                By phone number: <span className="text-white">03001234968</span>
              </li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
